# Generated by Django 4.0.4 on 2022-10-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_scoreboard_remove_student_user_delete_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='question_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_marks',
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=10),
        ),
    ]
