# Generated by Django 4.0.4 on 2022-10-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_course_question_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
    ]
